[build]
  command = "ng build"
  publish = "dist/emotion-esc"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200