[build]
  command = "ng build"
  publish = "dist/emotion-esc" 

# Required for Angular routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Optional: For debugging redirects
[[redirects]]
  from = "/_redirects"
  to = "/_redirects"
  status = 200